kubernetes:
  deploy:
    config:
      repo: git@github.com:bcaldwell/k8s-config.git
      folder: selfops/ynab-importers
    namespace: selfops
    helmChart: deploy/ynab-importers
    releaseName: ynab-importers
