version: 2
jobs:
  release-docker:
    docker:
      - image: benjamincaldwell/ci-scripts

    working_directory: /go/src/github.com/bcaldwell/ci-scripts

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build and pushing docker image
          command: ci-scripts docker/build_and_push_image --docker-images-dockerRepo benjamincaldwell/ynab-importers

  deploy:
    docker:
      - image: benjamincaldwell/ci-scripts

    environment:
      CI_SCRIPTS_CONFIG: ./.circleci/ci_scripts.yml

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            # k8s cluster
            - "46:38:75:f2:09:9f:c5:8b:84:32:4f:02:66:c6:5c:6b"
            # github deploy key
            - "b4:db:e5:d9:77:38:e8:0d:18:32:60:2e:ec:44:e4:5c"

      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export DOCKER_IMAGE_DEPLOY_TAG="${CIRCLE_SHA1}"' >> $BASH_ENV

      - run:
          name: Deploying
          command: ci-scripts kubernetes/deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - release-docker
      - deploy:
          requires:
            - release-docker
        filters:
          branches:
            only: master
        context: kubernetes
