version: 2
jobs:
  release-docker:
    docker:
      - image: benjamincaldwell/ci-scripts

    working_directory: /go/src/github.com/bcaldwell/ci-scripts

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build and pushing docker image
          command: ci-scripts docker/build_and_push_image --docker-images-dockerRepo benjamincaldwell/ynab-importers

  deploy:
    docker:
      - image: benjamincaldwell/ci-scripts

    environment:
      CLUSTER_DOMAIN: benjamincaldwell.ca

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "80:58:cd:21:56:5a:81:10:54:58:0c:a3:d1:4b:04:b8"
            - "46:38:75:f2:09:9f:c5:8b:84:32:4f:02:66:c6:5c:6b"

      - run:
          name: Deploying
          command: ci-scripts kubernetes/deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - release-docker
      - deploy:
          requires:
            - release-docker
