version: 2
jobs:
  release-docker:
    docker:
      - image: benjamincaldwell/ci-scripts

    working_directory: /go/src/github.com/bcaldwell/ci-scripts

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build and pushing docker image
          command: ci-scripts docker/build_and_push_image --docker-images-dockerRepo benjamincaldwell/ynab-importers

  deploy:
    docker:
      - image: cimg/base:2020.01

    steps:
      - run:
          name: Updating docker image in k8s-config
          command: |
            export FOLDER=selfops/ynab-importers
            curl -H "Authorization: token $GITHUB_TOKEN" -H 'Accept: application/vnd.github.v3.raw' https://api.github.com/repos/bcaldwell/k8s-config/contents/scripts/update_docker_image.sh | bash /dev/stdin ${FOLDER} ${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - release-docker
      - deploy:
          requires:
            - release-docker
          filters:
            branches:
              only: master
          context: bot-github
