apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ynab-importers.fullname" . }}
  labels:
    {{- include "ynab-importers.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ynab-importers.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ynab-importers.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: YNAB_IMPORTER_EJSON_SECRET_KEY
              value: /var/run/secrets/ejson/ejson-key
            - name: YNAB_IMPORTER_SECRETS_FILE
              value: /app/src/secrets.ejson
            - name: PYTHONUNBUFFERED
              value: "0"
            {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: secrets-volume
              mountPath: /app/src/secrets.ejson
              subPath: secrets.ejson
            - name: ejson-key-volume
              mountPath: /var/run/secrets/ejson
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      volumes:
        - name: secrets-volume
          secret:
            secretName: {{ .Values.volumes.secrets.ynabImporters }}
        - name: ejson-key-volume
          secret:
            secretName: {{ .Values.volumes.secrets.ejsonKey }}